# Site settings
title: Flux
name: Human
description: "Flux"

domain: fluxdpsd.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://fluxdpsd.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /fluxdpsd.gitub.io/      # place folder name if the site is served in a subfolder


# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

